package de.caritas.cob.consultingtypeservice.api.service.permission;

public enum Permission {
  LANGUAGE_FORMAL_SETTINGS,
  NOTIFICATION_SETTINGS,
  SEND_FURTHER_STEPS_MESSAGE_SETTINGS,
  SEND_SAVE_SESSION_DATA_MESSAGE_SETTINGS,
  VIDEO_CALL_ALLOWED_SETTINGS,
  WELCOME_MESSAGE_SETTINGS,
}
