openapi: 3.0.1

info:
  title: Definition for Topic API
  description: This information will be replaced by the SpringFox config information
  version: 0.0.1

paths:
  /topic-groups:
    get:
      tags:
        - topic-groups
      summary: 'Get all topic groups'
      operationId: getAllTopicGroups
      responses:
        200:
          description: OK - successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicGroupsDTO'
        204:
          description: NO CONTENT - no content found
        401:
          description: UNAUTHORIZED - no/invalid token
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
  /topic:
    get:
      tags:
        - topic-controller
      summary: 'Get all topics'
      operationId: getAllTopics
      responses:
        200:
          description: OK - successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TopicDTO'
        204:
          description: NO CONTENT - no content found
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
  /topic/{id}:
    summary: Represents a topic
    description: This resource represents an individual topic in a system.
    get:
      tags:
        - topic-controller
      summary: 'Gets a topic by its id [Not yet implemented]'
      operationId: getTopicById
      parameters:
        - name: id
          in: path
          description: Topic ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicDTO'
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        404:
          description: Not found
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
  /topic/public:
    summary: 'Represents the public allowed topic data'
    get:
      tags:
        - topic-controller
      summary: 'Get all public available (active) topics [Authorization: no-auth]'
      operationId: getAllActiveTopics
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TopicDTO'
        404:
          description: Not found
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition

  /topicadmin:
    post:
      tags:
        - topic-admin-controller
      summary: 'Creates a new topic [Authorization: Role: topic-admin]'
      operationId: createTopic
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/TopicMultilingualDTO'
      responses:
        200:
          description: OK - successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicMultilingualDTO'
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
    get:
      tags:
        - topic-admin-controller
      summary: 'Get all topics'
      operationId: getAllTopicsAsAdmin
      responses:
        200:
          description: OK - successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TopicDTO'
        204:
          description: NO CONTENT - no content found
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
  /topicadmin/{id}:
    summary: Represents a topic
    description: This resource represents an individual topic in a system.
    get:
      tags:
        - topic-admin-controller
      summary: 'Gets a topic with translation by its id [Not yet implemented]'
      operationId: getTopicWithTranslationById
      parameters:
        - name: id
          in: path
          description: Topic ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicMultilingualDTO'
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        404:
          description: Not found
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
    put:
      tags:
        - topic-admin-controller
      summary: 'Updates a topic [Authorization: Role: topic-admin] [Not yet implemented]'
      operationId: updateTopic
      parameters:
        - name: id
          in: path
          description: Topic ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/TopicMultilingualDTO'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicMultilingualDTO'
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        409:
          description: CONFLICT - unique constraint validation fails
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition


components:
  schemas:
    TopicGroupsDTO:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - items
          properties:
            items:
              type: array
              items:
                type: object
                required: [ id, name, topicIds ]
                properties:
                  id:
                    type: integer
                    example: 12132
                  name:
                    type: string
                    example: "Topic group name"
                    maxLength: 100
                  topicIds:
                    type: array
                    items:
                      type: integer
    FallbackAgencyId:
      type: integer
      format: int32
    WelcomeMessage:
      type: string
      format: int32
      maxLength: 200
    FallBackUrl:
      type: string
      format: url
      maxLength: 200
    TopicDTO:
      type: object
      required:
        - name
        - description
      properties:
        id:
          type: long
          example: 12132
        name:
          type: string
          example: "Topic name"
          maxLength: 100
        description:
          type: string
          example: "Description"
          maxLength: 100
        internalIdentifier:
          type: string
          example: "identifier for data exports for example: alcohol"
          maxLength: 50
        status:
          type: string
          example: "Active"
          maxLength: 10
        createDate:
          type: string
        updateDate:
          type: string
        fallbackAgencyId:
          $ref: '#/components/schemas/FallbackAgencyId'
        fallbackUrl:
          $ref: '#/components/schemas/FallBackUrl'
        welcomeMessage:
          $ref: '#/components/schemas/WelcomeMessage'

    TopicMultilingualDTO:
      type: object
      required:
        - name
        - description
      properties:
        id:
          type: long
          example: 12132
        name:
          type: object
          additionalProperties:
            type: string
        description:
          type: object
          additionalProperties:
            type: string
        internalIdentifier:
          type: string
          example: "identifier for data exports for example: alcohol"
          maxLength: 50
        status:
          type: string
          example: "Active"
          maxLength: 10
        createDate:
          type: string
        updateDate:
          type: string
        fallbackAgencyId:
          $ref: '#/components/schemas/FallbackAgencyId'
        fallbackUrl:
          $ref: '#/components/schemas/FallBackUrl'
        welcomeMessage:
          $ref: '#/components/schemas/WelcomeMessage'

    Translation:
      type: object
      required:
        - lang
      properties:
        lang:
          type: string
          example: "en"
        value:
          type: string
          maxLength: 100
          example: "Lorem"